language: node_js # elm is installed from npm (see install below)
node_js: node     # use "latest" version of Node.js

env:
- ELM_VERSION=0.18.0 ELM_TEST=0.18.12

install: # install specific versions of elm & elm-test
- npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST
- elm package install --yes # install main project dependencies

script:
- elm-test --verbose
- echo "yalla"