language: node_js
node_js: node

# install specific versions of elm & elm-test
install:
- npm install

script:
- npm run build

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - examples/elm-stuff/build-artifacts
    - examples/elm-stuff/packages
    - $HOME/.npm
    - node_modules
